version: "3.8" #what version of docker compose syntax we using

services: #what containers we want to run and each service is a container
  db: #postgresql db container
    image: postgres:15 #this is a standard img so no dockerfile needed
    environment: #enviornment sets up username, password and db name 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports: #postgres default port 
      - "5432:5432"

  api: #my fastapi container
    build: . #this says that we build from our dockerfile in current folder
    ports: #same as before, we define ports
      - "8000:8000"
    depends_on: #this means to start db container before api 
      - db
    environment: #passes db conn string to app so it knows where to find postgresql
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todoapp