upstream fastapi { 
    server api:8000;
}

server { #defines how nginx handles imcoming requestw
    listen 80; #listens on port 80 

    location / { #matches all incoming url
        proxy_pass http://fastapi; #forwards req to fast api container (like GET, PUT, POST, etc.)
        #the headers we manually tell nginx what to pass on
        proxy_set_header Host $host; #passes original host header so fast api knows what domain was requested
        proxy_set_header X-Real-IP $remote_addr; #passes ip adress of client, so it knows who makes req
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #standard header, tracks chain of proxies the req went through
    }
}